[build]
  functions = "functions"
  publish = "build"
  environment = { AWS_LAMBDA_JS_RUNTIME = "nodejs10.x" }

[[redirects]]
  from = "/image"
  to = "https://www.bing.com/HPImageArchive.aspx"
  status = 200