[build]
  functions = "functions"
  publish = "build"
  command = "npm run netlify"
  environment = { AWS_LAMBDA_JS_RUNTIME = "nodejs10.x" }

[[redirects]]
  from = "/bing"
  to = "https://www.bing.com/HPImageArchive.aspx"
  status = 200

[[redirects]]
  from = "/image"
  to = "https://bing-wallpaper.netlify.com/.netlify/functions/image"
  status = 200